apiVersion: v1
kind: Service
metadata:
  name: gost-svc
  namespace: vpn
  labels: 
    app: gost
spec:
  type: LoadBalancer
  # externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gost